FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /src

# התקנת dotnet-ef כ-global tool
RUN dotnet tool install --global dotnet-ef

# להוסיף ל-PATH
ENV PATH="$PATH:/root/.dotnet/tools"

COPY . .

RUN dotnet restore

EXPOSE 8080

CMD ["dotnet", "watch", "run", "--urls=http://0.0.0.0:8080"]