# 1️⃣ בחירת תמונה בסיסית
FROM node:20-alpine AS build

WORKDIR /app

# 2️⃣ קבלת ARG מה-build
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

# 3️⃣ התקנת תלויות ובניית הפרויקט
COPY package*.json ./

RUN npm install

RUN npm ls vite
RUN ls node_modules/.bin

# הוספת type definitions
RUN npm install --save-dev @types/node @types/react @types/react-dom

COPY . .

RUN npm run build

# 4️⃣ שלב ההגשה
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]