services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}

    ports:
      - "1434:1433"

    volumes:
      - sql_data:/var/opt/mssql

  server:
    build:
      context: ./server/ApiPharm
      dockerfile: dockerfile.dev

    env_file:
      - ./server/ApiPharm/.env

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;
        Database=${DB_NAME};
        User Id=${DB_USER};
        Password=${DB_PASSWORD};
        TrustServerCertificate=True;

    volumes:
      - ./server/ApiPharm:/src

    ports:
      - "8080:8080"

    depends_on:
      - sqlserver

  client:
    build:
      context: ./client/my-react-app
      dockerfile: dockerfile.dev

    env_file:
      - ./client/my-react-app/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./client/my-react-app:/app
      - /app/node_modules

    ports:
      - "5173:5173"
    command: sh -c "npm run dev -- --host"

    depends_on:
      - server

volumes:
  sql_data: