services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  server:
    build:
      context: ./server/ApiPharm
      dockerfile: Dockerfile
      args:
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USER: ${DB_USER}
        DB_NAME: ${DB_NAME}
    env_file:
      - ./server/ApiPharm/.env
    environment:
      ConnectionStrings__DefaultConnection: >
        Server=sqlserver;
        Database=${DB_NAME};
        User Id=${DB_USER};
        Password=${DB_PASSWORD};
        TrustServerCertificate=True;
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver

  client:
    build:
      context: ./client/my-react-app
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    env_file:
      - ./client/my-react-app/.env
    ports:
      - "80:80"
    depends_on:
      - server

volumes:
  sql_data: